<?php
/**
 * Arnaud Amant <contact@arnaudamant.fr>
 */
namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends EntityRepository
{
    public function allForCompany($company_id)
    {
        $query = $this->getEntityManager()
            ->createQuery('
                SELECT p, c FROM AppBundle:Customer p
                LEFT JOIN p.company c
                WHERE c.id = :id'
            )->setParameter('id', $company_id);

        return $query->getResult();
    }
}
