<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Company;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;

/**
 * TaxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxRepository extends EntityRepository
{
    public function getLast(Company $company)
    {
        try {
            $query = $this->getEntityManager()->createQuery('
              SELECT t.year, t.month FROM AppBundle:Tax t 
              WHERE t.company = :company
              ORDER BY t.id DESC
            ')
                ->setMaxResults(1)
                ->setParameter('company', $company->getId());
            
            return $query->getSingleResult();
        } catch (NoResultException $e) {
            return null;
        } catch (NonUniqueResultException $e){
            return null;
        }
    }
}
