<?php

namespace Aamant\InvoiceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceRepository extends EntityRepository
{
    public function findFullById($id)
    {
        $query = $this->getEntityManager()
            ->createQuery('
                SELECT p, c FROM AamantInvoiceBundle:Invoice p
                LEFT JOIN p.items c
                WHERE p.id = :id'
            )->setParameter('id', $id);

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function findFullWithUserById($id)
    {
        $query = $this->getEntityManager()
            ->createQuery('
                SELECT p, c FROM AamantInvoiceBundle:Invoice p
                LEFT JOIN p.items c
                JOIN p.customer cu
                WHERE p.id = :id'
            )->setParameter('id', $id);

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
