<?php

namespace Aamant\InvoiceBundle\Entity;

use Aamant\UserBundle\Entity\Company;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * PaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends EntityRepository
{
    public function findForList(Company $company)
    {
        $query = $this->getEntityManager()
            ->createQuery('
                SELECT payment, customer, invoice FROM AamantInvoiceBundle:Payment payment
                JOIN payment.customer customer
                JOIN payment.invoice invoice
                ORDER BY payment.date DESC
            ');

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function paymentPerYear(Company $company)
    {
        $query = $this->getEntityManager()->getConnection()->prepare('
                SELECT YEAR(p.date) as year, SUM(p.total) as total FROM payment p
                WHERE company_id = :company
                GROUP BY YEAR(p.date)
                ORDER BY YEAR(p.date) DESC
            ');
        $query->execute(['company' => $company->getId()]);

        try {
            return $query->fetchAll();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function paymentPerMonthForYear(Company $company, $year)
    {
        $query = $this->getEntityManager()->getConnection()->prepare('
                SELECT MONTH(p.date) as month, SUM(p.total) as total FROM payment p
                WHERE company_id = :company
                AND YEAR(p.date) = :year
                GROUP BY MONTH(p.date)
            ');
        $query->execute(['company' => $company->getId(), 'year' => $year]);

        try {
            return $query->fetchAll();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function paymentPerYearAndMonth(Company $company)
    {
        $query = $this->getEntityManager()->getConnection()->prepare('
                SELECT YEAR(p.date) as year, MONTH(p.date) as month, SUM(p.total) as total FROM payment p
                WHERE company_id = :company
                GROUP BY YEAR(p.date), MONTH(p.date)
            ');
        $query->execute(['company' => $company->getId()]);

        try {
            return $query->fetchAll();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
