<?php

namespace Aamant\InvoiceBundle\Entity;

use Aamant\UserBundle\Entity\Company;
use Doctrine\ORM\EntityRepository;

/**
 * PaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends EntityRepository
{
    public function findForList(Company $company)
    {
        $query = $this->getEntityManager()
            ->createQuery('
                SELECT payment, customer, invoice FROM AamantInvoiceBundle:Payment payment
                JOIN payment.customer customer
                JOIN payment.invoice invoice
            ');

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
