<?php

namespace Aamant\InvoiceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TimeTrackerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeTrackerRepository extends EntityRepository
{
}
