aamant_statistic:
    resource: "@AamantStatisticBundle/Controller/"
    type:     annotation
    prefix:   /

aamant_settings:
    resource: "@AamantSettingsBundle/Controller/"
    type:     annotation
    prefix:   settings

aamant_invoice:
    resource: "@AamantInvoiceBundle/Controller/"
    type:     annotation
    prefix:   sales

aamant_customer:
    resource: "@AamantCustomerBundle/Controller/"
    type:     annotation
    prefix:   customers

aamant_user:
    resource: "@AamantUserBundle/Controller/"
    type:     annotation
    prefix:   users

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
